collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5300752
  brandStrength: 0.8237774
  lightness: 0.8426423
  brandColors:
    - '#3A2715'
    - '#6E3842'
    - '#B3222E'
    - '#5C81AC'
    - '#9A9276'
  rhythmicContrast: 0.7310287
typography_spectrum: 0.5934479
layout_spectrum: 0.6281619
name: Great1
